### PR TITLE
Release/update cesium and hotjar script

### PR DESCRIPTION
**Pull request by weberjavi**
This release will:
-  Update Cesium version.
-  Add Hotjar script to allow some analytics to happen.

### CODE REVIEW

**Comment by simaob** [comment]
Hmm, there seem to be a lot more commits than what is in the description. Is this bringing any new features?

**Comment by weberjavi** [comment]
Yeah I've noticed that there's a pending deploy PR https://github.com/Vizzuality/half-earth/pull/407 and I brought all that into this one.

**Comment by weberjavi** [comment]
We where just waiting to Chris to understand that Stories where gonna be taken from Contentful after that release
[Basecamp thread](https://basecamp.com/1756858/projects/13899003/todos/368397110)

**Comment by simaob** [comment]
We'd need to check with @benlaken if this is being used at all?

**Comment by weberjavi** [comment]
You're talking about Stories?

**Comment by weberjavi** [comment]
BTW also `Species tags colours` and `Google analytics` are inside this never deployed deploy

**Comment by weberjavi** [comment]
So @benlaken , @simaob should we deploy everything?

**Pull request closed without merging**
