### PR TITLE
Feature/stories interaction

### PR DESCRIPTION
**Pull request by weberjavi**
This PR adds `places to watch` and `stories` layers interactions ([pt](https://www.pivotaltracker.com/story/show/160683580), [pt](https://www.pivotaltracker.com/story/show/160791556))
Adds tooltip component([pt](https://www.pivotaltracker.com/story/show/160683943))
It also adds zoom to a grid visible altitude on `double click` ([pt]())
It also changes `bivarate` plot ([pt](https://www.pivotaltracker.com/story/show/161096128)) and some small changes on texts ([pt](https://www.pivotaltracker.com/story/show/161094688))

TODO: 
interaction on `conservations areas` layer and `pledges` layer
info button on `bivarate`

kapture 2018-10-10 at 16 11 43

### CODE REVIEW

**Comment by weberjavi** [comment]
Hey there @simaob & @benlaken this PR is ready to review.
Further improvements to tooltip behaviour should be made in order to provide a better experience

**Comment by weberjavi** [comment]
@simaob check the changes ☝️

**Comment by simaob** [comment]
I see why you felt the buffer was important. Probably a bit tricky to find a balance between applying the buffer or not. So not sure if it's best to leave it out or in at the moment. What are your thoughts?

**Comment by weberjavi** [comment]
I've updated with a smaller size, but for now I think is the 'best' solution until we handle that properly.
Also updated layers opacity on terrain

**Pull request merged**
